server:
  tomcat:
    uri-encoding: UTF-8
  port: 38667
  connection-timeout: 7200
  servlet:
    context-path: /pps
spring:
  dataSourseList: data-source1        #数据源列表名称 与下面数据源对应  第一个默认为主数据库
  data-source1:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源类型
    database:                                     #数据源基本配置
      username: root
      password: xxxxxxxxxxxxxxxxxxxx
      driver_class_name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://ip/pps-lyt-room?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    mybatisConfig:
      type-aliases-ackageList:                       #别名
      mapperXmlLocation:                             #mapper.xml  位置
        - classpath:mapper/*.xml
      mapperLocation:                                #mapper位置
        - com.pps.movie.mapper
      configuration:
        map-underscore-to-camel-case: true
        #org.apache.ibatis.logging.stdout.StdOutImpl日志只会打印到控制台
        #org.apache.ibatis.logging.slf4j.Slf4jIml会把日志打印到指定log文件
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        global-config:
          #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
          db-config:
            id-type: AUTO

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 统一设置日期格式
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      location: d:/uploadtest
pagehelper:
  helperDialect: mysql                           #分页插件方言选择
  reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  supportMethodsArguments: true
#security自定义的框架
mysecurity:
  permitUrl:                                 #允许不登录就能访问的url
    - /images/**
    - /templates/**
  loginUrl:  /login                  #表单 登录页url
  logoutUrl: /logout                 #登录退出url
  openVerifyCode: false              #是否开启验证码登录处理 验证码参数默认：verifyCode
  validateCodeParam: verifyCode      #会从session里面拿这个参数 作为验证码
  verifyCodeUrl:  /verifyCode        #获取验证码url
  failureUrl: /login/error           #关于账户权限发生错误失败跳转的地址  暂时没有用
  smsMessage: /sms/get/yanzhengma
  openRequestLog: false               #网络请求是否打印
  canCrossOrigin: true               #是否生成跨域访问filter  建议生产环境取消
  openConfigUser: true               #是否开启本地测试用户  若开启 则configUsers不能为空 为一个数组 并且权限固定为ROLE_ADMIN
  configUser: '[{"username":"admin","password":"123"},{"username":"n1","password":"x1111111"}]'
  sms:
     openSms: false
     smsLoginUrl: /sms/login
     smsMessage:  /sms/get/yanzhengma #短信验证码获取
     mobileParameter: phone           #网络请求的电话号码参数
     codeParameter: code              #网络请求里面的验证码
     sessionParam:  code              #产生验证码时存到session的参数名
     sessionPhoneParam: phone         #存到session里面的应该为一个map  这是map的电话号码参数
     sessionCodeParam:  code          #存到session里面的应该为一个map  这是map的验证码参数
  jwt:
      enable: true                   #开启jwt登录  开启后登陆成功后返回前端token  下次带token 可以授权
      jwtLoginUrl: /jwt/login         #没有用到
      filter: /pps/jwt/**
      expire: 604800
      secret: aHR0cHM6Ly9teS5vc2NoaW5hLm5ldC91LzM2ODE4Njg=
      headerParam: authorization                 # header 带token的参数名
  resources:
    static-locations: classpath:/static/, classpath:/templates/

#netty im 聊天服务设置
pps:
  netty:
    im:
      enable : true
      port: 38666
      websocketPath: /pps

#fastdsf 文件上传
  fastdfs:
    enable: true                         #开启自动配置
    racker_servers: ip:22122  #服务器地址 如果多个 逗号分隔
    urlPrefix:ip #访问地址前缀 可以为空
#http 访问工具启动器
  http:
    enable: true
    enableforHttp1: true
    theadForHttp1: 1
    enableforHttp0: false
    theadForHttp0: 1
    enableforPhantom: true
    path: C:\phantomjs-2.1.1-windows\bin\phantomjs.exe     #/usr/bin/phantomjs
    buffSize: 1

#日志级别
logging:
  level:
    com.pps: debug
